In [3]:
import numpy as np
import matplotlib as plt
import scipy

In [4]:
def f(x):
    return np.sin(x/5.0)*np.exp(x/10.0) + 5 * np.exp(-x/2.0)

In [34]:
a = np.array([[1.0, 1.0, 1.0, 1.0], [1.0, 4.0, 16.0, 64.0], [1.0, 10.0, 100.0, 1000.0], [1.0, 15.0, 225.0, 15.0**3]])
b = np.array([f(1), f(4), f(10), f(15)])
w = np.linalg.solve(a,b)

In [35]:
print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Решение системы:\n", w)


Матрица A:
 [[1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03]
 [1.000e+00 1.500e+01 2.250e+02 3.375e+03]]
Вектор b:
 [3.25221687 1.74684595 2.50541641 0.63522142]
Решение системы:
 [ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [36]:
print(a.dot(w))

[3.25221687 1.74684595 2.50541641 0.63522142]


In [43]:
file_obj = open('submission-2.txt', 'w')
string = ''
for i in range(len(w)):
    string = string + str(w[i])+ ' '

file_obj.write(string)
file_obj.close()
!cat submission-2.txt

4.362641535118072 -1.2955258656948434 0.1933368470215116 -0.008235651173320554 